title: "TrendFlow"
description: "생활을 가볍게 만드는 트렌드 기록형 블로그"
url: "https://trend.it.kr"
baseurl: ""
lang: ko
timezone: Asia/Seoul

markdown: kramdown
permalink: /posts/:title/

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: post

exclude:
  - README_BLOG_OPERATING_GUIDE.md
  - trendflow_site_*.zip
  - tools
